### ISSUE TITLE
Reproduction issues

### ISSUE THREAD

**Issue by luoshunchong** [waynewu6250/LABAN#1]
When I read your paper, I was attracted by your amazing idea. but when I reproduce your code according to redme, I don't get the result in your paper. I don't know if I have set it wrong. can you tell me the details of the reproduction process?For example, it seems that there is no seed set in your code and I want to get the results in the paper, how do I do that?
Thank you very much!

**Comment by waynewu6250** [comment]
We report the overall average score based on many intent splits of different random seeds. There could be some variations between each split (Some may be large due to seen and unseen intent correlations). Here is only the sample code for just one split and we can get the similar results for FSPS if you run python bert_zsl.py train/test directly.
